### ISSUE TITLE
Dotfiles 101: Create a video covering the usage of dotfiles within Gitpod

### ISSUE THREAD

**Issue by axonasif** [gitpod-io/community-office-hours#13]

**Comment by loujaybee** [comment]
Sounds great! You are the dotfiles Guru, @axonasif 😆 

In other news... I'm kinda wondering if we want to keep this type of content item here, or whether it's better in one of the existing places like website repo or content backlog? Just conscious we have content items everywhere 🙈 

* https://github.com/orgs/gitpod-io/projects/31/views/1
* https://github.com/gitpod-io/website
* https://github.com/gitpod-io/website/projects/1

**Comment by axonasif** [comment]
Hey @loujaybee, thanks for jumping in!
One of my QTB goals is to become more efficient at vocal communication, so I've been working on that and as well as improving my video editing skills for the past few weeks. So this is kind of a _wanna-do_ thing to get an initial draft done myself.

And BTW, instead of notion I want to use github-projects _like other cool kids_ to track my projects as a part of the community team to share with @pawlean in our 1:1s, so she's aware of what I'm working on. I'll obviously have to collab with the content team to get it in shape before publishing.

I don't want to get the attention of content team early because I'm not really sure of the date or priorities.

**Comment by pawlean** [comment]
As we discussed in the Community Sync (internal) [[1](https://www.notion.so/gitpod/Community-Sync-ca2d492199504fd9b95ad60860d6753d)]:

- Let's make this video a screencast because it's valuable content! See [this](https://www.notion.so/gitpod/Creating-Screencasts-1966a775126a43d6bfbaa5c0def639f9) document on how to format this video 
- Can you share this in the `content` Slack channel as an FYI so that the content team are aware?

In terms of the content, it might be good to get a structure together, from the top of my head:

1.  Welcome / intro on the video
2. What are dotfiles?
3. How do you get them set up on Gitpod?
4. Some dotfiles examples -> maybe your favourites/community favourites
5. Conclusion with a CTA to community

WDYT?

**Comment by axonasif** [comment]
Sounds like a good plan!
I have posted on #content channel to take a look into issues with the video tag and track these on their content backlog if they want 🙏

**Comment by pawlean** [comment]
**Suggestions as discussed in our 1:1:**

- Use [Descript](https://www.descript.com/) to edit video
- Use Loom or MacOS recording app to record your screen without the floating head (i.e. you on camera)

**Comment by axonasif** [comment]
It was covered by https://www.youtube.com/watch?v=00dif9QWXNU 🙌
