### ISSUE TITLE
Format Community Highlights 2022

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/community-office-hours#42]
We recently decided to move the community highlights from an internal Notion document to this repo to encourage the community to contribute their own work in case we miss them. 

I had already gone through and re-formatted all of the **[highlights from 2023](https://github.com/gitpod-io/community/blob/main/community-highlights/2023.md)** but wanted some help with **[re-formatting 2022's highlights.](https://github.com/gitpod-io/community/blob/main/community-highlights/2022.md)**

There are guidelines on best practices [here](https://github.com/gitpod-io/community/blob/main/community-highlights/README.md#guidelines).

**Comment by SuperGrut** [comment]
@pawlean I am super interested to contribute to it. Could you please assign it to me...

**Comment by ghostdevv** [comment]
@akash19coder I've assigned you to this issue! Let me know if you need anything :pray:

**Comment by siddarth2810** [comment]
@pawlean I have started working on this ! Completed till September 30th 2022, should i raise a PR after everything is done or would it be too much to review at once ?

**Comment by axonasif** [comment]
Hi @siddarth2810, thank you for taking the initiative on this! I'm sorry to inform you that Community Highlights have been discontinued. However, for the sake of completeness, we may still be able to merge your changes since you've already worked on this. Feel free to raise a PR with your changes so far.

What you did is commendable! Just a small tip from me for your future opensource contribution endeavors: It's always worth asking for confirmation before working on a public issue like this one to avoid risking your time 😇

Have a good week 👋

**Comment by siddarth2810** [comment]
hey @axonasif, thank you soo much. I’m sorry for any inconvenience caused, and I’ll definitely keep your advice in mind for future contributions. I'll go ahead and raise a PR with the completed changes soon !

**Comment by pawlean** [comment]
You still rock for contributing, @siddarth2810! 😄
